version: '3.8'

services:
    api:
        image: star-wars-alternative-world-api
        build: ./api
        restart: unless-stopped
        ports:
            - $API_PORT:$API_PORT
        networks:
            - app-network

    app:
        image: star-wars-alternative-world-app
        command: yarn prod
        build: ./app
        restart: unless-stopped
        ports:
            - $APP_PORT:5000 # Serve will use port 5000
        networks:
            - app-network
        depends_on:
            -   db

    db:
        image: postgres
        restart: unless-stopped
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_DB: ${DB_NAME}
        volumes:
            - db-data:/var/lib/postgresql

networks:
    app-network:
        driver: bridge

volumes:
    db-data:
        driver: local
