version: '3.8'

services:
    api:
        image: star-wars-alternative-world-api
        build: ./api
        restart: unless-stopped
        ports:
            - $API_PORT:$API_PORT
        env_file: 
            - ./.env
        environment:
            - DB_HOST=db
            - DB_PORT=5432
        networks:
            - app-network
        depends_on:
            - db

    app:
        image: star-wars-alternative-world-app
        command: yarn prod
        build: ./app
        restart: unless-stopped
        ports:
            - $APP_PORT:5000 # Serve will use port 5000
        environment:
            - REACT_APP_API_URL=http://$API_HOST:$API_PORT
        networks:
            - app-network
        depends_on:
            - db

    db:
        image: postgres:12
        restart: unless-stopped
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: $DB_PASSWORD
            POSTGRES_USER: $DB_USER
            POSTGRES_DB: $DB_NAME
        networks:
            - app-network
        volumes:
            - db-data:/var/lib/postgresql

networks:
    app-network:
        driver: bridge

volumes:
    db-data:
        driver: local
