version: '3.8'

services:
    api:
        image: star-wars-alternative-world-api
        build: ./api
        command: yarn dev
        ports:
            - $API_PORT:$API_PORT
        env_file: 
            - ./.env
        environment:
            - DB_HOST=db
            - DB_PORT=5432
        networks:
            - app-network
        volumes:
            - ./api/:/usr/src/app
            - /usr/src/app/node_modules

    app:
      image: star-wars-alternative-world-app
      command: yarn start
      build: ./app
      ports:
          - $APP_PORT:3000 # Create React App will use port 3000
      networks:
          - app-network
      depends_on:
          - db
      volumes:
          - ./app/:/usr/src/app
          - /usr/src/app/node_modules

    db:
      image: postgres
      environment:
          POSTGRES_PASSWORD: $DB_PASSWORD
          POSTGRES_USER: $DB_USER
          POSTGRES_DB: $DB_NAME
      volumes:
          - db-data:/var/lib/postgresql

networks:
    app-network:
        driver: bridge

volumes:
    db-data:
        driver: local
